### PR TITLE
Improved support for Java 11+

### PR DESCRIPTION
**Pull request by Col-E**
Mirror of the [PR on the upstream repo](https://github.com/jmockit/jmockit1/pull/736) - (Copying description below)

********

Encountered some compatibility issues with a project due to outdated bytecode handling.

Other changes under the hood:

- Change bytecode handling to explicitly fail rather than assume a type in switch cases _(Assisted in debugging, and failing makes the cause more clear than undefined behavior caused by ignoring the issue with fallback behavior)_
- Use full names instead of shorthand for constants _(minor legibility improvement)_
- Use _Objenesis_ instead of direct sun reflection-factory for instance creation.
- Remove JUnit platform exclusion in `pom.xml`, resolving some failures with IntelliJ integration

## Validity

I tested up to Java 17 using the maven tool-chain plugin with all tests passing when running `mvn test`. Though, using IntelliJ's JUnit runner one specific case fails _(though I think this is due to test environment pollution since it doesn't fail when ran isolated or from maven directly)_

### CODE REVIEW

**Comment by Col-E** [comment]
Any suggestions for the [applet test failures](https://github.com/Col-E/jmockit1/actions/runs/3207845740/jobs/5243148539)? Is there some setup I'm missing?

**Comment by hazendaz** [comment]
@Col-E Sorry for delay, didn't have watcher turned on here.  Its on now.  I actually pulled your PR more directly as I did not see this, I haven't pushed it up yet.  Will do so shortly as looking at some javadoc issues showing up.  I suspect either this PR will show no more changes or auto close as applied.  Letting it at least try to build even if the applet issue.  I'm leaning towards just deleting the applets as I believe no browsers support any more anyways.

**Comment by Col-E** [comment]
> Will do so shortly as looking at some javadoc issues showing up.

👍 

>  I'm leaning towards just deleting the applets as I believe no browsers support any more anyways.

A total of 0 people weep 😏

**Comment by hazendaz** [comment]
painfully sticking to jdk 8 to allow the release process for time being (I prefer to use 17).  something wrong with javadocs which is not super surprising based on how poorly maven javadoc plugin works in general.  usually get some idea of issues but none really.  running mvn javadoc:javadoc gave me some clues in modules not under my release parent control but none of the fixes I tried helped.  However, able to release.  Doing so now...

**Pull request merged**
