### PR TITLE
Feature/aztec1

### PR DESCRIPTION
**Pull request by asterix1000**

### CODE REVIEW

**Comment by asterix1000** [comment]
ok

**Comment by hazendaz** [comment]
@asterix1000 Did you intend to close this after opening?

**Comment by asterix1000** [comment]
yes sorry. i need to test my reactivate-changes first

**Comment by hazendaz** [comment]
@asterix1000 Well when you have something working, please break up concepts.  On Deencapsulation, I think we keep that as a deprecated feature and suggest using powermock but then again maybe this repo has more oomph on this continuation effort so its not a big deal.  Powermock seems dead too :(

**Comment by hazendaz** [comment]
@asterix1000 One other thing, personally I have no use for the feature add back, I've long since ported > 1k repos over to powermock over last number of years but it was a pain at the time so this would be huge for those that have not updated and are stuck...so if that is working bring it anytime.

**Pull request closed without merging**
