### PR TITLE
Restore partial mocking of class literals via the Mocking api

### PR DESCRIPTION
**Pull request by jsolomon8080**
This is a WIP. Compiles but tests fail.

A rollback of: https://github.com/hazendaz/jmockit1/commit/825ab79cb79dcd67be3dc2d4291edeed30a3902a

Also a rollback of related commits:

https://github.com/hazendaz/jmockit1/commit/053e9ac21142c2488f75afdb7f3066a85b0ea041 https://github.com/hazendaz/jmockit1/commit/d3bcd4c90bbb4a17ca59b0164c272bc9ca803228 https://github.com/hazendaz/jmockit1/commit/853b63735a861241040061ecfd8d0b95a2b16f3c

However, commit https://github.com/hazendaz/jmockit1/commit/7cc93620c52ebbb1b5f15682ce4ab54521c5cc06 which came after this refactored this code making it difficult to apply them cleanly.

### CODE REVIEW

**Comment by hazendaz** [comment]
@jsolomon8080 Can you rebase this and see if possible to get working?

**Comment by jsolomon8080** [comment]
@hazendaz I don't think rebasing would help unless I misunderstand what you're asking. This change is already using close to the very latest code from your repository.

**Comment by hazendaz** [comment]
ok no worries.  I didn't look beyond it fails ci.

**Comment by hazendaz** [comment]
@jsolomon8080 Seems maybe there wasn't much interest for this.  Was this a blocker for you or have you gotten around its need?  I have not run into any more products at work that would have benefited from any more coming back.  Only thing I'm facing currently is getting this to work with jakarta namespace but not a huge need on that yet as that jump is very difficult for legacy apps in general and areas that made it had respective coverage so disabling some of the tests didn't harm coverage enough to matter.

If this is still needed, may just be you and I that try to bring it back.  At a minimum in that case, if you could rebase it off current master that would help.  I could then take a further look.  However, if it seems not worth it, maybe we close this out and just open an issue that points back to it so that its not sitting here needlessly.

**Comment by jsolomon8080** [comment]
We can close. Our codebase had some 2000 instances of this but I converted all of them to newer patterns. That was a pain but thankfully a one time transition. I'm happy to say that our code is now fully running on java 17 with all jmockit tests passing successfully.

However, we are about to start a jakarta transition of our own so I may be right back here working with you to get jmockit in a state using the latest namespace. We shall see. Thank you for circling back on this issue.

**Comment by jsolomon8080** [comment]
Closing.

**Pull request closed without merging**
