### PR TITLE
Restore mocking of many classes from java.util

### PR DESCRIPTION
**Pull request by jsolomon8080**
Rolls back much of this commit:

```
commit 536c2c73b5c6aa0137f92acda78ba84607c2446c
Date:   Thu Jan 3 20:59:00 2019 -0300

    Added java.util interfaces and java.util.jar types to the list of unmockable types; closes #573.
```

Reintroduces this issue: https://github.com/jmockit/jmockit1/issues/573

which is fine IMO. You can't just break everyone's code that had come to rely on mocking these classes. Users can workaround #573 or similar issues.

The following classes are once again mockable:
```
import java.util.AbstractSet;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Queue;
import java.util.Set;
import java.util.SortedMap;
import java.util.SortedSet;
```

### CODE REVIEW

**Comment by jsolomon8080** [comment]
I was wondering if merging this will break any current jmockit users and I do not think it will. This feature is another caveat emptor. Anyone using jmockit 1.45+ cannot have any @Mock etc statements on any of these classes because the tests would immediately fail with "class is unmockable". Anyone using jmockit prior to 1.45 might have mocked these classes successfully and now they cannot upgrade to 1.45+ without changing their code. This is fine if changing their code is tractable.

After this change is merged, users can once again get mysterious errors like the one seen in issue #573, but they can also upgrade without changing their code, or they can successfully mock these classes as long as they can navigate the pitfalls of doing so.

I think merging this capability is a documentation issue.

**Comment by hazendaz** [comment]
@jsolomon8080 I'm fine with this, can you possibly write up the caveat emptor items for the README so its clear that some of this is considered bad behaviour.

**Comment by jsolomon8080** [comment]
@hazendaz I will submit a PR with an update to the README. My update will include a summary features that have been added back since you forked from the original jmockit. I would also like to include a statement on this project vowing to adhere to proper semantic versioning. That is, no backward incompatible changes will be made unless the version number increments by a major version.

**Comment by hazendaz** [comment]
@jsolomon8080 I had been trying to keep the version on par with original but its been so long now that maybe its time to break from that as it was not semantic to start with.  There was a jmockit 2 in the works long ago but that fizzled out at some point.  So due to that, I had stuck with 1.x.x (where I made it look semantic otherwise) but I've also introduced breaking changes like requiring java 11 since.  However, if this keeps on progressing longer term, there may be value in cutting to 2.0.0 and trying to version it right going forwards.

**Pull request merged**
